In [1]:
import numpy as np

In [5]:
np.__version__

'2.4.4'

## Create & Read

## Id array

In [8]:
arr1 = np.array([1,2,3,4,5])

In [9]:
arr1

array([1, 2, 3, 4, 5])

In [10]:
type(arr1)

numpy.ndarray

In [11]:
arr1.shape

(5,)

In [12]:
arr1.dtype

dtype('int64')

In [13]:
arr1.ndim

1

In [14]:
arr1.size

5

# 2D array

In [16]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [17]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
arr2.ndim

2

In [19]:
arr2.shape

(2, 3)

In [20]:
arr2.dtype

dtype('int64')

In [23]:
arr2.size

6

## 3D array

In [27]:
arr3 = np.array([[[1,9,2],[3,5,1]], [[2,4,6],[7,3,2]],[[9,3,6],[5,2,8]]])

In [25]:
arr3

[[[1, 9, 2], [3, 5, 1]], [[2, 4, 6], [7, 3, 2]], [[9, 3, 6], [5, 2, 8]]]

In [28]:
arr3.ndim

3

In [29]:
arr3.shape

(3, 2, 3)

In [30]:
arr3.size

18

## Create Random Array

In [31]:
randomArr = np.random.rand(3,2,3)

In [32]:
randomArr

array([[[0.83275983, 0.36360053, 0.27148732],
        [0.16491431, 0.36182459, 0.79461897]],

       [[0.8530846 , 0.96455355, 0.38451218],
        [0.09494398, 0.04925606, 0.52237253]],

       [[0.39851763, 0.74669156, 0.0323818 ],
        [0.33828218, 0.20604215, 0.78791717]]])

In [33]:
randomArr.dtype

dtype('float64')

In [34]:
zeroes = np.zeros([3,2,3])

In [35]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [36]:
zeroes.ndim

3

In [37]:
zeroes.shape

(3, 2, 3)

In [38]:
full = np.full([3,2,3], 9)

In [39]:
full

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])

In [40]:
ones = np.ones((3,2,3))

In [41]:
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [42]:
arr3

array([[[1, 9, 2],
        [3, 5, 1]],

       [[2, 4, 6],
        [7, 3, 2]],

       [[9, 3, 6],
        [5, 2, 8]]])

In [43]:
arr3[0]

array([[1, 9, 2],
       [3, 5, 1]])

In [44]:
arr3[0][0][2]

np.int64(2)

In [45]:
arr3

array([[[1, 9, 2],
        [3, 5, 1]],

       [[2, 4, 6],
        [7, 3, 2]],

       [[9, 3, 6],
        [5, 2, 8]]])

In [46]:
arr3[0:2]

array([[[1, 9, 2],
        [3, 5, 1]],

       [[2, 4, 6],
        [7, 3, 2]]])

In [47]:
arr3[0:3]

array([[[1, 9, 2],
        [3, 5, 1]],

       [[2, 4, 6],
        [7, 3, 2]],

       [[9, 3, 6],
        [5, 2, 8]]])

In [48]:
arr3[-1]

array([[9, 3, 6],
       [5, 2, 8]])

In [49]:
arr3[-1][0][1]

np.int64(3)

In [50]:
arr3[1,0,1]

np.int64(4)

## Update & Delete numpy array

In [51]:
a1 = np.random.rand(2,3,2)

In [52]:
a1

array([[[0.80197753, 0.78539182],
        [0.32613092, 0.37344137],
        [0.24341444, 0.34018003]],

       [[0.8061433 , 0.88831438],
        [0.31411649, 0.38528257],
        [0.21792836, 0.44687215]]])

In [53]:
a2 = np.random.rand(2,3,2)

In [54]:
a2

array([[[0.25180828, 0.56782479],
        [0.17217201, 0.81469226],
        [0.26402439, 0.98898643]],

       [[0.02900476, 0.80926539],
        [0.31714816, 0.25153566],
        [0.15097766, 0.56449597]]])

## Basic Math operations

In [55]:
np.add(a1,a2)
np.subtract(a1,a2)
np.divide(a1,a2)
np.multiply(a1,a2)

array([[[0.20194458, 0.44596495],
        [0.05615062, 0.30423979],
        [0.06426735, 0.33643344]],

       [[0.02338199, 0.71888208],
        [0.09962147, 0.0969123 ],
        [0.03290231, 0.25225753]]])

In [56]:
np.add(a1,a2)

array([[[1.05378581, 1.35321662],
        [0.49830293, 1.18813363],
        [0.50743883, 1.32916646]],

       [[0.83514806, 1.69757977],
        [0.63126465, 0.63681823],
        [0.36890602, 1.01136812]]])

In [57]:
np.subtract(a1,a2)

array([[[ 0.55016926,  0.21756703],
        [ 0.15395891, -0.44125089],
        [-0.02060995, -0.6488064 ]],

       [[ 0.77713854,  0.07904899],
        [-0.00303167,  0.13374692],
        [ 0.0669507 , -0.11762382]]])

In [58]:
np.divide(a1,a2)

array([[[ 3.18487362,  1.38315874],
        [ 1.89421569,  0.45838335],
        [ 0.92193921,  0.34396835]],

       [[27.79348152,  1.09767993],
        [ 0.99044086,  1.5317215 ],
        [ 1.44344772,  0.79163036]]])

In [59]:
np.multiply(a1,a2)

array([[[0.20194458, 0.44596495],
        [0.05615062, 0.30423979],
        [0.06426735, 0.33643344]],

       [[0.02338199, 0.71888208],
        [0.09962147, 0.0969123 ],
        [0.03290231, 0.25225753]]])

In [61]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2,4)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)

In [62]:
sqrt

np.float64(5.0)

In [63]:
abs

np.int64(2)

In [64]:
power

np.int64(16)

In [65]:
log

np.float64(3.2188758248682006)

In [66]:
mins

np.float64(0.21792836107712832)

In [67]:
maxs

np.float64(0.9889864312631368)

## Update

In [68]:
arr3

array([[[1, 9, 2],
        [3, 5, 1]],

       [[2, 4, 6],
        [7, 3, 2]],

       [[9, 3, 6],
        [5, 2, 8]]])

In [69]:
arr3[0,0,2] = 500

In [70]:
arr3

array([[[  1,   9, 500],
        [  3,   5,   1]],

       [[  2,   4,   6],
        [  7,   3,   2]],

       [[  9,   3,   6],
        [  5,   2,   8]]])

In [71]:
arr3.sort()

In [72]:
arr3

array([[[  1,   9, 500],
        [  1,   3,   5]],

       [[  2,   4,   6],
        [  2,   3,   7]],

       [[  3,   6,   9],
        [  2,   5,   8]]])

In [73]:
arr3.shape

(3, 2, 3)

In [74]:
arr3_reshape = arr3.reshape(2,3,-1)

In [75]:
arr3_reshape

array([[[  1,   9, 500],
        [  1,   3,   5],
        [  2,   4,   6]],

       [[  2,   3,   7],
        [  3,   6,   9],
        [  2,   5,   8]]])

In [76]:
arr3_reshape.shape

(2, 3, 3)

## Appending & Inserting

## Appending

In [79]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

## Create a new array

In [81]:
new_array = np.ones((3,2,3))

In [82]:
appd = np.append(zeroes, new_array, axis=0)

In [83]:
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [84]:
appd = np.append(zeroes, new_array, axis=1)

In [85]:
appd

array([[[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]]])

## Inserting

In [86]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [87]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [88]:
inserted_array = np.insert(zeroes, 1,  new_array, axis=0)

In [89]:
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [93]:
inserted_array = np.insert(zeroes, 2,  new_array, axis=0)
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [94]:
inserted_array = np.insert(zeroes, 3,  new_array, axis=0)
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

# Delete

In [95]:
arr4 = np.random.rand(3,2,3)

In [96]:
arr5 = np.delete(arr4,0, axis=1)

In [97]:
arr5

array([[[0.26988503, 0.45528223, 0.81234292]],

       [[0.86894769, 0.87360139, 0.44437243]],

       [[0.31757105, 0.11937228, 0.88455689]]])

In [98]:
np.save("new_array", arr5)

In [99]:
np.load("new_array.npy")

array([[[0.26988503, 0.45528223, 0.81234292]],

       [[0.86894769, 0.87360139, 0.44437243]],

       [[0.31757105, 0.11937228, 0.88455689]]])